### PR TITLE
Auto works with strange types if they are None

### PR DESCRIPTION
**Pull request by forki**
trying to reproduce https://github.com/fable-compiler/Fable.ReactGoogleMaps/pull/4 

but it seems to work here.
(I still think we should merge the additional tests)

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
It seems CI is not enabled for PRs, did you try to run them locally. We also need to run them on the .NET side, which is a bit more complicated because Thoth.Json.Net lives in a different repo now. 

> Maybe you can help me convince @MangelMaxime to put the two versions in a single repo again ;)

**Comment by forki** [comment]
Yes. Those new tests are green locally. But I tried to reproduce my real
issue and failed

Alfonso Garcia-Caro <notifications@github.com> schrieb am Do., 2. Mai 2019,
12:25:

**Comment by alfonsogarciacaro** [comment]
Should be fixed on .NET side by https://github.com/thoth-org/Thoth.Json.Net/pull/7

**Comment by forki** [comment]
So it was an issue on dotnet side? But not in js?

Alfonso Garcia-Caro <notifications@github.com> schrieb am Fr., 3. Mai 2019,
20:39:

**Comment by MangelMaxime** [comment]
@forki With this PR I am able to reproduce the problem in Thoth.Json.Net

@alfonsogarciacaro With your PR, the tests added by @forki are now working.

@forki @alfonsogarciacaro You can't reproduce the error on "Fable" side because we don't have exactly the same implementation of the auto encoder/decoder. Because, on dotnet side we need to use what we call "boxEncoder/boxDecoder" in order to preserve the type info.

And the Fable side is implemented correctly to handle your case. I am going to release a new version to fix your problem. Just let me the time to merge all the PR etc. :)

**Comment by alfonsogarciacaro** [comment]
Not sure if it's related but for some reason at least in JS the coders seem to be generated lazily, I still don't know why :/

**Comment by forki** [comment]
Ok awesome. Now I understand why I couldn't repro. That allows me to sleep
fine ;-)

Alfonso Garcia-Caro <notifications@github.com> schrieb am Fr., 3. Mai 2019,
21:50:

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Well we don't use the same implementation for this particular encoder on Fable side:

```fs
t.GenericTypeArguments.[0] |> autoEncoder extra isCamelCase |> option |> boxEncoder
```

But yes, I am not sure why it doesn't fail.

**Comment by MangelMaxime** [comment]
Released in version 3.1.0

Thank you to both of you for the help.

**Pull request merged**
