### PR TITLE
Support caching of de/encoders independent from casing

### PR DESCRIPTION
**Pull request by SCullman**

### CODE REVIEW

**Comment by SCullman** [comment]
I'm beginning to realize the complexity.
```fsharp
/// ATTENTION: Use this only when other arguments (isCamelCase, extra) don't change
```
It is not `isCamelCase` but to find a hash for `extra`.

**Comment by MangelMaxime** [comment]
Perhaps this is a naive solution, but because `Extra` coder is a black box, we could change the type from 

```fs
type ExtraCoders = Map<string, BoxedEncoder * BoxedDecoder>
```

to 

```fs
type ExtraCoder =
    {
        Guid : Guid
        Encoder : BoxedEncoder
        Decoder : BoxedDecoder
    }

type ExtraCoders = Map<string, ExtraCoder>
```

This means we should be able to generate a hash using the `Guids` and in order to not recompute the hash each time we can also change

```fs
type ExtraCoders = Map<string, ExtraCoder>
```

to 

```fs
type ExtraCoders = 
    {
        Hash : String
        Coders : Map<string, ExtraCoder>
    }
```

It's kind of the first time I need to generate/work with hash, so perhaps my solution have some problem. What do you think?

**Comment by SCullman** [comment]
> Is your last commit generating a correct hash for the extra coders?
It is not really a hash, instead a string with the source of the coder. I did not want to calculate a hash for that, as it might take too mush time, as this must be done on every access.
--- 
I like the idea with the `Guid`.  The hash of the  ExtraCoders might be as simple as all concated Guids from its inner coders. We still need to generate a key `Fullname + Casing + ExtraCoders.Hash` for each call of an Auto coding.

**Comment by MangelMaxime** [comment]
> We still need to generate a key `Fullname + Casing + ExtraCoders.Hash` for each call of an Auto coding.

Indeed but because `ExtraCoders.Hash` is already stored in the variable it's just a direct concatenation of 3 strings which should be ok I think.

The "slow part" will be the initialization of the `myExtraCoders` variable because it will recalculate the "hash" each time we had a coder to it.

**Comment by SCullman** [comment]
What about no Guid for ExtraCoder, instead the hash of ExtraCoders is a Guid. If the map is modified with Extra.with..., a new GUID is set.

**Comment by MangelMaxime** [comment]
> What about no Guid for ExtraCoder, instead the hash of ExtraCoders is a Guid. If the map is modified with Extra.with..., a new GUID is set.

It makes sense indeed.

**Comment by SCullman** [comment]
Or the Guide is just set on first read.

Maxime Mangel <notifications@github.com> schrieb am Mo., 14. Okt. 2019,
17:42:

**Comment by MangelMaxime** [comment]
I am rebasing your PR to the latest version of develop

**Comment by MangelMaxime** [comment]
Thank you for the PR, I am merging it in develop.

And I am working on making Thoth.Json.Net match the same set of features as Thoth.Json.

**Comment by SCullman** [comment]
Thank you.

**Comment by SCullman** [comment]
@MangelMaxime , are you going to release the next days? I would like to continue my work on Thoth.Fetch.   
You must also know that a new release of Thoth.Fetch (and  Thoth.Json.Net/ enum support) will trigger  a cascade of releases in other projects (well, some of them internal but I would like to [promote](https://github.com/SCullman/DNN.Fable.Connector) fable even more in the DNN Community).

**Comment by MangelMaxime** [comment]
> @MangelMaxime , are you going to release the next days?

That's my idea yes. For me Thoth.Json is ready for a release, all the feature are completed now (I removed `seq 'T` support because I don't know how to do it in Thoth.Json.Net). 

So now, I am just working on making Thoth.Json.Net ready too (already have the tests adapted).

**Comment by MangelMaxime** [comment]
@SCullman 

What's the motivation behind 

```fs
type internal Key =
    | Coder of InternalCoder
    | NewCoder
```


[source](https://github.com/thoth-org/Thoth.Json/pull/29/files#diff-c20e415512a2adab6200404994d348c8R11-R19)

This is causing a problem with Thoth.Json.Net:

> The value 'withBigInt' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible

Can't we just use `System.Guid.NewGuid().ToString()` for any coders added without regard if they are coming from `Thoth.Json(.Net)` or the user code?

**Comment by SCullman** [comment]
> Can't we just use System.Guid.NewGuid().ToString() for any coders added without regard if they are coming from Thoth.Json(.Net) or the user code?

Yes, we can. 
My motivation was to have always equal keys for known coders. Maybe this is a premature optimization.

**Pull request merged**
