### PR TITLE
Don't throw when union doesn't contain field values

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
`makeUnion` function contains a shortcut when the `values` array is empty. However, this prevents the code from going to `mixedArray` which has a safeguard when the `values` array doesn't correspond to the number of union case fields. So if `values = [||]` but the union case has one or more fields, the code will throw instead of showing a typed error. Example:

```fsharp
type Foo = Foo of int

let foo = Decode.Auto.fromString("[\"Foo\"]")
```

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro This PR conflicts with the changes introduced in #118 

Can you please have a look?

**Comment by alfonsogarciacaro** [comment]
Hi @MangelMaxime! Sorry, it took so long. I've fixed the merge conflict and added a test 👍

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Ahah no problem, I was making you wait even longer last time :)

I will have a look at your changes thank you.

**Comment by MangelMaxime** [comment]
Thank you, it has been released

**Pull request merged**
