### PR TITLE
WIP: add encoders, decoders for [u]int[8/16] & float32

### PR DESCRIPTION
**Pull request by 0x53A**
closes https://github.com/thoth-org/Thoth.Json/issues/11

### CODE REVIEW

**Comment by 0x53A** [comment]
how do I check the bundle size?

**Comment by MangelMaxime** [comment]
Hum for the bundle size, I think you can compile the tests in production mode (need a change in webpack.config.js).

Or inside a real-world project.

**Comment by 0x53A** [comment]
The goal is to verify that tree-shaking still works, right?

So I'll create a small test project that only uses the auto (de)serializers.

This should then only grow by a few bytes between master and branch, and not pull in any new libs.

**Comment by MangelMaxime** [comment]
> The goal is to verify that tree-shaking still works, right?

Yes indeed. And yes, I am expecting the bundle size to increase of a few bytes because it needs to add the new functions in the bundle because they are used by auto (de)serializers

**Comment by alfonsogarciacaro** [comment]
Looks good to me! I assume the small increase in bundle size will likely be compensated by the refactoring to share code with the integer decoders :)

**Comment by MangelMaxime** [comment]
Thank you for the feedback @alfonsogarciacaro 

For info, I am not merging this PR because it's still marked as WIP and also the tests don't cover every case.

For example, we are missing:
- Encoder tests
- Success cases for decoder tests

**Comment by 0x53A** [comment]
Sorry, I currently find only sporadic motivation for OSS. Give me one or two days, I'll ping (and remove the WIP).

**Comment by MangelMaxime** [comment]
@0x53A No worries

My goal is not to push/rush you. I was just doing a list of the missing things. Like that, we know what still needs to be done.

**Comment by MangelMaxime** [comment]
Hello, 

When working on the `enum` support, I wrote the `[u]int[8/16]` encoders/decoders. After, seeing this PR, I undo my work to copy/paste from your work as it was better (it use a helper to mutualize the code).

I will close the PR when reading the new version.

**Comment by MangelMaxime** [comment]
Closed in favour of https://github.com/thoth-org/Thoth.Json/pull/28

Thank you, @0x53A for the initial work.

**Comment by 0x53A** [comment]
Thank you for taking care of it

**Pull request closed without merging**
