### PR TITLE
Auto encoding doesn't work with decimal

### PR DESCRIPTION
**Pull request by forki**
Something broke here. This used to work with older fable

### CODE REVIEW

**Comment by MangelMaxime** [comment]
This is expected you need to use `extra coders` to add support for `decimal`

[See the documentation](https://mangelmaxime.github.io/Thoth/json/v3.html#decoding-int64-decimal-or-bigint)

**Comment by forki** [comment]
Expected? I'd consider decimal are very common type on .net - it's the one
you are supposed to use for money. Shouldn't it be in the box?

Maxime Mangel <notifications@github.com> schrieb am Do., 2. Mai 2019, 12:58:

**Comment by MangelMaxime** [comment]
We don't put decimal by default because it increases a lot the bundle size.

I don't think I will now had it back by default because I released version 3 as stable. We had a beta phase going for several months but didn't get feedback from it so I had to take a decision.

You can create a wrapper function to automatically provides the extra coders you need.

**Comment by forki** [comment]
it's not a criticism. I'm just trying to discuss this from user view. 

(I'm sorry for not verifying things earlier, but updating big projects takes a lot of time. especially since so many parts changed in the fable ecosystem)

**Comment by MangelMaxime** [comment]
> it's not a criticism. I'm just trying to discuss this from user view.

I know and sorry :) It's just that I have multiple people encountering issues due to changes between major release and sometimes it's hard to handle all of it in a serene way. :)

> (I'm sorry for not verifying things earlier, but updating big projects takes a lot of time. especially since so many parts changed in the fable ecosystem)

And as always, I am welcoming feedbacks. 

So to explains the situation, this version 3 of the library is (was) trying to reduce the bundle size in order to pass the webpack limit that was discussed in the SAFE template repo. So we decided, to remove the "not so common" types from the code support and especially the types having a big impact.

And we were able to take this decision because we added the extra coder features so people using Auto decoders a lot like SAFE stack users can extend the supported types.

**Comment by forki** [comment]
ok. let me try to add that decoder now and I'll give feedback if I see something that could make it easier for users.

**Comment by forki** [comment]
ok. it's not that hard to do. actually it's good. Only question is: what do I want to set for isCamelCase?

image

**Comment by MangelMaxime** [comment]
`isCamelCase` allows you to set the representation of the JSON keys.

- `isCamelCase = true` -> `{ "firstname" : "maxime" }`
- `isCamelCase = false` -> `{ "Firstname" : "maxime" }`

If you don't care you can just leave to its default value and use `?extra = encoder`.

You probably should name your variable `encoder` to something like `coder` or `extraCoder`.

We use the word `coder` because it contains both `encoder` and `decoder` definition.

**Comment by forki** [comment]
Ok thanks. So last issue for me is about the latlng stuff and I don't know
how to repro.

Maxime Mangel <notifications@github.com> schrieb am Do., 2. Mai 2019, 16:06:

**Comment by MangelMaxime** [comment]
If you only have the `latlng` type to support you can add a custom decoder for it, just so the generation work.

*If you are serializing/de-serializing the type for real, please write actual decoder/encoder*

```fs
open Thoth.Json

type Custom =
    interface end

let customDecoder : Decoder<Custom> =
    Decode.succeed Unchecked.defaultof<Custom>

let customEncoder (value : Custom) : JsonValue =
    Encode.nil

let coder =
    Extra.empty
    |> Extra.withCustom customEncoder customDecoder
```

I am setting up CI for the Thoth repos and trying to set up a Windows VM locally in order to test/fix things.

**Comment by forki** [comment]
image


this works, but I'd rather not do it ;-)

**Comment by MangelMaxime** [comment]
Trust me nothing can go wrong :trollface: 

I know, I am giving you a temporary solution until we can repro or and fix it. If I can't fix the windows tests, I will try to repro your situation myself and see what can be done.

**Comment by forki** [comment]
Yeah. I'm fine with the workaround. More concerned why I can't repro. Bugs
me a bit

Maxime Mangel <notifications@github.com> schrieb am Fr., 3. Mai 2019, 19:48:

**Comment by MangelMaxime** [comment]
I will close this PR as it is an "expected" behaviour

**Pull request closed without merging**
