### PR TITLE
Fix CultureInfo for decimal and windows ci

### PR DESCRIPTION
**Pull request by Freymaurer**
As requested i ran all tests on my windows machine and only newtonsoft tests were failing. Any decimal was written to string with `,` as separator. Not sure if this was a windows or computer settings issue. I added a very dirty fix for this.

While checking for the bug, i added a ftestCase option to the runner and fixed some orders on the tests aligning them with test message output.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thanks for looking into it.

Regarding the globalisation, I am not sure what to do about it. As Fable doesn't support it there is a risk there are others problem that could exist. In the past, the idea was we don't handle it (which is not necessary a good or better idea).

In your case, I think you had an issue because you have a german machine which use German globalisation.

Perhaps, we could set `<InvariantGlobalization>true</InvariantGlobalization>` in the test project file of Newtonsoft. It should disable globalisation for running the tests and would avoid forcing a globalisation in the core library for now.

https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization

**Comment by Freymaurer** [comment]
I really like your idea using `<InvariantGlobalization>true</InvariantGlobalization>`, but after some testing it seems like it does not affect the code execution at all. I tried adding it to both `Thoth.Json.Newtonsoft` and `Thoth.Json.Core`, but tests fail.

```xml
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--This has no effect-->
    <InvariantGlobalization>true</InvariantGlobalization>
</PropertyGroup>
```

In contrast i verified, that InvarianCulture should be correct using:

```fsharp
// this works as intended
let inline decimal (value: decimal) = value.ToString(CultureInfo.InvariantCulture) |> string
```

I tried looking for a reason why this does not work, but found nothing.

Edit: I check the CulturInfo on runtime with `System.Globalization.CultureInfo.CurrentCulture |> printfn "Current Culture: %A"` and it returned "Current Culture: de-DE". So yeah, it does in fact not work as intended.

But i noticed you were using `CulturInfo.Invariant` at multiple occasions. So i tried it for decimal but python does not like it 😅 

`let inline decimal (value: decimal) = value.ToString(CultureInfo.InvariantCulture) |> string`

image

I tried debugging the exact change required, but because of the several layers of abstraction i failed. But (!), i noticed that this should run, as in Fable 4.6.0 it runs as intended, while in 4.8.1 it fails. I will open an issue in Fable for this.

**Comment by Freymaurer** [comment]
fixed in https://github.com/fable-compiler/Fable/pull/3661, so maybe we can use that after the release

**Comment by Freymaurer** [comment]
Btw. I had some time and checked the windows issue. One part of the problem might have been the python version in the latest windows image. As it used python 3.9 and 3.10 is required for match cases (At least thats what ChatGPT told me 😅 ).

In addition i had to set python encoding to utf-8, because pyxpecto uses these emojis in its console output.

The next pyxpecto version offers a `--silent` option mimiking expecto behavior. Otherwise the tests pass now, but ... i guess they should not?

image

**Comment by MangelMaxime** [comment]
> n contrast i verified, that InvarianCulture should be correct using:
> 
> ```fsharp
> // this works as intended
> let inline decimal (value: decimal) = value.ToString(CultureInfo.InvariantCulture) |> string
> ```

Indeed, we used `CultureInfo.InvariantCulture` in the past as a workaround these situations.

Thank you for looking into the issue, indeed the CI should not succeed. Perhaps, I need to check for the exit code or pyxpecto needs to do something different on failure. I need to test the behaviour when the others test runners fails.

**Comment by Freymaurer** [comment]
> Thank you for looking into the issue, indeed the CI should not succeed. Perhaps, I need to check for the exit code or pyxpecto needs to do something different on failure. I need to test the behaviour when the others test runners fails.

The beta version of pyxpecto will also explicitly call exit with code instead of returning "just" an integer, maybe this will fix this issue

**Comment by Freymaurer** [comment]
@MangelMaxime the new exit code logic works like a charm, so the only test not passing is a DateTime test, maybe this is the issue you are currently working on? 

Hopefully these changes help you :)

**Comment by MangelMaxime** [comment]
Sorry your PR has been closed when I merged my branch into main...

I wanted to have the CI running for your branch, I am handling the situation now.

Thanks a lot for your times, I am checking your PR as we speak

**Pull request closed without merging**
