### PR TITLE
[WIP] Add Extra.withCustomPredicate

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
**EDIT**: Please don't merge yet, I'm having issues to adapt this to Thoth.Json.Net. It may not be a feasible approach.

I wanted to make the auto coders easy to use and hide most of the machinery to generate them. However, sometimes you need to access it to serialize some generic types, like dictionaries. This PR adds `Extra.withCustomPredicate` which enables adding custom dictionary coder, for example, to be used with `Auto`. The downside is users need to deal with boxed coders for the generic arguments, not sure if there's a way to improve the API.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I am not sure to understand the reason behind this PR. 

I think you are already able to customise/override the auto decoder/encoder behaviour using the actual API no?

**Comment by alfonsogarciacaro** [comment]
Imagine you want to add a custom coder for Dictionary (from `System.Collections.Generic`). Right now you can do it for a Dictionary with specific generic args (e.g. `Dictionary<string, int>`) but it's not possible to do it for _any_ dictionary. This PR tries to enable that, it's working for Fable but it's giving problems on .NET because of the casting of generic types.

Anyways, actually my problem was related to the debugger so I'm trying to fix that for now and keep this on hold :)

**Comment by MangelMaxime** [comment]
Ah ok I see thanks for the explanations. :)

**Comment by MangelMaxime** [comment]
I am closing this PR for now, because it's far behind the latest version. 

So it's will probably be easier to copy/paste the changes

**Pull request closed without merging**
